system ParticleSystem1
{
    technique 
    {
        material                                ParticleUniverse/Fire
        default_particle_width                  3
        default_particle_height                 3
        default_particle_depth                  3
        renderer                                Billboard
        {
            render_queue_group                  80
        }
        emitter                                 Point 
        {
            time_to_live                        dyn_random
            {
                min                             3
                max                             6
            }
            velocity                            dyn_random
            {
                min                             1.8
                max                             2.4
            }
        }
        affector                                Colour Affector0
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                Scale Affector1
        {
            xyz_scale                           dyn_random
            {
                min                             0.2
                max                             2
            }
        }
    }
}
